
POST http://localhost:9090/screens
Content-Type: application/json

{
  "name": "inox",
  "seatInfo": {
	"A": {
	  "numberOfSeats": 10,
	  "aisleSeats": [
		0,
		5,
		6,
		9
	  ]
	},
	"B": {
	  "numberOfSeats": 15,
	  "aisleSeats": [
		1,
		5,
		6,
		9
	  ]
	},
	"D": {
	  "numberOfSeats": 20,
	  "aisleSeats": [
		0,
		5,
		6,
		9
	  ]
	},
    "E": {
	  "numberOfSeats": 50,
	  "aisleSeats": [
		5,
		5,
		6,
		9
	  ]
	}
  }
}

###
